{% set name = "docspec" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/docspec-{{ version }}.tar.gz
  sha256: 4fd3709425804c818de29a2dc98f77e270d39c7bfae10c9f75c899df220b9c38

build:
  number: 0
  noarch: python
  entry_points:
    - docspec = docspec.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4.0
  run:
    - databind.core >=1.0.0,<2.0.0
    - databind.json >=1.0.0,<2.0.0
    - python >=3.7,<4.0

test:
  imports:
    - docspec
  commands:
    - pip check
    - docspec --help
  requires:
    - pip

about:
  home: https://pypi.org/project/docspec/
  summary: Docspec is a JSON object specification for representing API documentation of programming languages.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - NiklasRosenstein
